apiVersion: apps/v1
kind: Deployment
metadata:
  name: tp-04-busy-box-deployment
  namespace: default
  labels:
    app: tp-04-busy-box-deployment
spec:
  selector:
    matchLabels:
      app: tp-04-busy-box-deployment
  replicas: 5
  template:
    metadata:
      labels:
        app: tp-04-busy-box-deployment
    spec:
      containers:
        - name: tp-04-busy-box-deployment
          image: ghcr.io/yassineder/midl-tp-04-busy-box
          resources:
            limits:
              memory: "256Mi"
              cpu: "250m"
          ports:
            - name: nodejs-port
              containerPort: 3000
      restartPolicy: Always
